version: '2'
services:
  sicapuc20201-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/sicapuc20201/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sicapuc20201
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
